// ============================================================
// Vital Security PLC — Payroll System — Shared Types
// ============================================================

export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  SYSTEM_ADMIN = 'SYSTEM_ADMIN',
  HR_ADMIN = 'HR_ADMIN',
  FINANCE_OFFICER = 'FINANCE_OFFICER',
  OPERATIONS = 'OPERATIONS',
  GUARD = 'GUARD',
  HEAD = 'HEAD',
  CEO = 'CEO',
}

export enum EmployeeCategory {
  GUARD = 'GUARD',
  OFFICE_STAFF = 'OFFICE_STAFF',
}

export enum EmployeeStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  TERMINATED = 'TERMINATED',
  ON_LEAVE = 'ON_LEAVE',
  CONTRACTED = 'CONTRACTED',
}

export enum Gender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
}

export enum GuardPosition {
  GUARD = 'GUARD',
  SITE_LEADER = 'SITE_LEADER',
}

export enum EmploymentType {
  PERMANENT = 'PERMANENT',
  CONTRACT = 'CONTRACT',
  TEMPORARY = 'TEMPORARY',
}

export enum SiteType {
  COMMERCIAL = 'COMMERCIAL',
  RESIDENTIAL = 'RESIDENTIAL',
  INDUSTRIAL = 'INDUSTRIAL',
  GOVERNMENT = 'GOVERNMENT',
}

export enum SiteStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
}

export enum CompanyStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}

export enum PayrollPeriodStatus {
  DRAFT = 'DRAFT',
  OPEN = 'OPEN',
  CLOSED = 'CLOSED',
  LOCKED = 'LOCKED',
}

export enum PayrollRecordStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  UNDER_FINANCE_REVIEW = 'UNDER_FINANCE_REVIEW',
  RATE_ENTERED = 'RATE_ENTERED',
  CALCULATED = 'CALCULATED',
  RETURNED = 'RETURNED',
  CHECKED = 'CHECKED',
  APPROVED = 'APPROVED',
  READY_FOR_PAYMENT = 'READY_FOR_PAYMENT',
  PAYMENT_PROCESSING = 'PAYMENT_PROCESSING',
  PAID = 'PAID',
  CANCELLED = 'CANCELLED',
}

export enum ShiftAssignmentSource {
  MANUAL = 'MANUAL',
  ROTATION = 'ROTATION',
}

export enum RotationStatus {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  PAUSED = 'PAUSED',
  ARCHIVED = 'ARCHIVED',
}

export enum RotationGuardStatus {
  ACTIVE = 'ACTIVE',
  PAUSED = 'PAUSED',
  REMOVED = 'REMOVED',
}

export enum StaffAttendanceStatus {
  PRESENT = 'PRESENT',
  ABSENT = 'ABSENT',
  PAID_LEAVE = 'PAID_LEAVE',
  UNPAID_LEAVE = 'UNPAID_LEAVE',
  SICK_LEAVE = 'SICK_LEAVE',
  HALF_DAY = 'HALF_DAY',
  HOLIDAY = 'HOLIDAY',
  WEEKEND = 'WEEKEND',
}

export enum PaymentMethod {
  BANK_TRANSFER = 'BANK_TRANSFER',
  CASH = 'CASH',
}

export enum LoanStatus {
  ACTIVE = 'ACTIVE',
  PAID_OFF = 'PAID_OFF',
  WRITTEN_OFF = 'WRITTEN_OFF',
}

export enum PensionTaxBase {
  NORMAL_SALARY_ONLY = 'NORMAL_SALARY_ONLY',
  GROSS_PAY = 'GROSS_PAY',
}

// --- Procurement & Purchasing Enums ---
export enum RFQStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  SENT_TO_VENDOR = 'SENT_TO_VENDOR',
  QUOTATION_RECEIVED = 'QUOTATION_RECEIVED',
  UNDER_EVALUATION = 'UNDER_EVALUATION',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
  PO_CREATED = 'PO_CREATED',
}

export enum POStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  APPROVED = 'APPROVED',
  SENT_TO_VENDOR = 'SENT_TO_VENDOR',
  PARTIALLY_RECEIVED = 'PARTIALLY_RECEIVED',
  FULLY_RECEIVED = 'FULLY_RECEIVED',
  CLOSED = 'CLOSED',
  CANCELLED = 'CANCELLED',
  REJECTED = 'REJECTED',
}

export enum GRNStatus {
  DRAFT = 'DRAFT',
  CONFIRMED = 'CONFIRMED',
  CANCELLED = 'CANCELLED',
}

export enum BillStatus {
  DRAFT = 'DRAFT',
  POSTED = 'POSTED',
  PARTIALLY_PAID = 'PARTIALLY_PAID',
  PAID = 'PAID',
  CANCELLED = 'CANCELLED',
}

export enum ContactType {
  COMPANY = 'COMPANY',
  INDIVIDUAL = 'INDIVIDUAL',
}

export enum ProductType {
  STOCKABLE = 'STOCKABLE',
  CONSUMABLE = 'CONSUMABLE',
  SERVICE = 'SERVICE',
}

// --- Permission Map (for RBAC) ---

export const PERMISSIONS = {
  USER_CREATE: 'user.create',
  USER_READ: 'user.read',
  USER_UPDATE: 'user.update',
  USER_DELETE: 'user.delete',
  EMPLOYEE_CREATE: 'employee.create',
  EMPLOYEE_READ: 'employee.read',
  EMPLOYEE_UPDATE: 'employee.update',
  EMPLOYEE_DELETE: 'employee.delete',
  SITE_CREATE: 'site.create',
  SITE_READ: 'site.read',
  SITE_UPDATE: 'site.update',
  COMPANY_CREATE: 'company.create',
  COMPANY_READ: 'company.read',
  COMPANY_UPDATE: 'company.update',
  GUARD_REGISTER: 'guard.register',
  GUARD_ASSIGN_SITE: 'guard.assign-site',
  GUARD_MODIFY_HOURS: 'guard.modify-hours',
  GUARD_ATTENDANCE_READ: 'guard-attendance.read',
  GUARD_ATTENDANCE_MANAGE: 'guard-attendance.manage',
  GUARD_ATTENDANCE_FUTURE: 'guard-attendance.future',
  GUARD_ATTENDANCE_SELF: 'guard-attendance.self',
  STAFF_ATTENDANCE_MANAGE: 'staff-attendance.manage',
  GUARD_PAYROLL_READ: 'guard-payroll.read',
  GUARD_PAYROLL_RATES: 'guard-payroll.rates',
  GUARD_PAYROLL_CALCULATE: 'guard-payroll.calculate',
  GUARD_PAYROLL_CHECK: 'guard-payroll.check',
  GUARD_PAYROLL_APPROVE: 'guard-payroll.approve',
  GUARD_PAYROLL_PAY: 'guard-payroll.pay',
  GUARD_PAYROLL_RETURN: 'guard-payroll.return',
  OFFICE_PAYROLL_CREATE: 'office-payroll.create',
  OFFICE_PAYROLL_RATES: 'office-payroll.rates',
  OFFICE_PAYROLL_APPROVE: 'office-payroll.approve',
  OFFICE_PAYROLL_PAY: 'office-payroll.pay',
  REPORT_READ: 'report.read',
  AUDIT_READ: 'audit.read',
  SETTINGS_READ: 'settings.read',
  SETTINGS_UPDATE: 'settings.update',
  PAYROLL_PERIOD_READ: 'payroll-period.read',
  PAYROLL_CONFIG_MANAGE: 'payroll-config.manage',
  ORGANIZATION_READ: 'organization.read',
  ORGANIZATION_MANAGE: 'organization.manage',
  ROTATION_READ: 'rotation.read',
  ROTATION_MANAGE: 'rotation.manage',
  ROTATION_GENERATE: 'rotation.generate',
  ROTATION_APPROVE: 'rotation.approve',
  ROTATION_PUBLISH: 'rotation.publish',
  ROTATION_OVERRIDE: 'rotation.override',

  // Procurement & Purchasing
  PURCHASE_READ: 'purchase.read',
  PURCHASE_CREATE: 'purchase.create',
  PURCHASE_UPDATE: 'purchase.update',
  PURCHASE_APPROVE: 'purchase.approve',
  PURCHASE_DELETE: 'purchase.delete',
  CONTACT_READ: 'contact.read',
  CONTACT_MANAGE: 'contact.manage',
  PRODUCT_READ: 'product.read',
  PRODUCT_MANAGE: 'product.manage',
  GRN_MANAGE: 'grn.manage',
  BILL_MANAGE: 'bill.manage',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  [UserRole.SUPER_ADMIN]: [
    PERMISSIONS.USER_READ, PERMISSIONS.USER_CREATE, PERMISSIONS.USER_UPDATE,
    PERMISSIONS.EMPLOYEE_CREATE, PERMISSIONS.EMPLOYEE_READ, PERMISSIONS.EMPLOYEE_UPDATE, PERMISSIONS.EMPLOYEE_DELETE,
    PERMISSIONS.SITE_CREATE, PERMISSIONS.SITE_READ, PERMISSIONS.SITE_UPDATE,
    PERMISSIONS.COMPANY_CREATE, PERMISSIONS.COMPANY_READ, PERMISSIONS.COMPANY_UPDATE,
    PERMISSIONS.GUARD_REGISTER, PERMISSIONS.GUARD_ASSIGN_SITE, PERMISSIONS.GUARD_MODIFY_HOURS,
    PERMISSIONS.GUARD_ATTENDANCE_READ, PERMISSIONS.GUARD_ATTENDANCE_MANAGE, PERMISSIONS.GUARD_ATTENDANCE_FUTURE,
    PERMISSIONS.STAFF_ATTENDANCE_MANAGE,
    PERMISSIONS.GUARD_PAYROLL_READ, PERMISSIONS.GUARD_PAYROLL_RATES, PERMISSIONS.GUARD_PAYROLL_CALCULATE,
    PERMISSIONS.GUARD_PAYROLL_CHECK, PERMISSIONS.GUARD_PAYROLL_APPROVE, PERMISSIONS.GUARD_PAYROLL_PAY, PERMISSIONS.GUARD_PAYROLL_RETURN,
    PERMISSIONS.OFFICE_PAYROLL_CREATE, PERMISSIONS.OFFICE_PAYROLL_RATES, PERMISSIONS.OFFICE_PAYROLL_APPROVE, PERMISSIONS.OFFICE_PAYROLL_PAY,
    PERMISSIONS.REPORT_READ, PERMISSIONS.AUDIT_READ, PERMISSIONS.SETTINGS_READ, PERMISSIONS.SETTINGS_UPDATE,
    PERMISSIONS.PAYROLL_PERIOD_READ, PERMISSIONS.PAYROLL_CONFIG_MANAGE,
    PERMISSIONS.ORGANIZATION_READ, PERMISSIONS.ORGANIZATION_MANAGE,
    PERMISSIONS.ROTATION_READ, PERMISSIONS.ROTATION_MANAGE, PERMISSIONS.ROTATION_GENERATE,
    PERMISSIONS.ROTATION_APPROVE, PERMISSIONS.ROTATION_PUBLISH, PERMISSIONS.ROTATION_OVERRIDE,
    PERMISSIONS.PURCHASE_READ, PERMISSIONS.PURCHASE_CREATE, PERMISSIONS.PURCHASE_UPDATE, PERMISSIONS.PURCHASE_APPROVE, PERMISSIONS.PURCHASE_DELETE,
    PERMISSIONS.CONTACT_READ, PERMISSIONS.CONTACT_MANAGE, PERMISSIONS.PRODUCT_READ, PERMISSIONS.PRODUCT_MANAGE,
    PERMISSIONS.GRN_MANAGE, PERMISSIONS.BILL_MANAGE,
  ],
  [UserRole.SYSTEM_ADMIN]: [
    PERMISSIONS.USER_CREATE, PERMISSIONS.USER_UPDATE, PERMISSIONS.USER_READ,
    PERMISSIONS.COMPANY_CREATE, PERMISSIONS.COMPANY_READ, PERMISSIONS.COMPANY_UPDATE,
    PERMISSIONS.EMPLOYEE_CREATE, PERMISSIONS.EMPLOYEE_READ, PERMISSIONS.EMPLOYEE_UPDATE, PERMISSIONS.EMPLOYEE_DELETE,
    PERMISSIONS.SETTINGS_READ, PERMISSIONS.SETTINGS_UPDATE, PERMISSIONS.AUDIT_READ,
    PERMISSIONS.GUARD_ATTENDANCE_READ,
    PERMISSIONS.ORGANIZATION_READ, PERMISSIONS.ORGANIZATION_MANAGE,
    PERMISSIONS.PURCHASE_READ, PERMISSIONS.PURCHASE_CREATE, PERMISSIONS.PURCHASE_UPDATE, PERMISSIONS.PURCHASE_APPROVE, PERMISSIONS.PURCHASE_DELETE,
    PERMISSIONS.CONTACT_READ, PERMISSIONS.CONTACT_MANAGE, PERMISSIONS.PRODUCT_READ, PERMISSIONS.PRODUCT_MANAGE,
    PERMISSIONS.GRN_MANAGE, PERMISSIONS.BILL_MANAGE,
  ],
  [UserRole.HR_ADMIN]: [
    PERMISSIONS.USER_READ, PERMISSIONS.EMPLOYEE_CREATE, PERMISSIONS.EMPLOYEE_READ, PERMISSIONS.EMPLOYEE_UPDATE, PERMISSIONS.EMPLOYEE_DELETE,
    PERMISSIONS.SITE_CREATE, PERMISSIONS.SITE_READ, PERMISSIONS.SITE_UPDATE,
    PERMISSIONS.COMPANY_CREATE, PERMISSIONS.COMPANY_READ, PERMISSIONS.COMPANY_UPDATE,
    PERMISSIONS.GUARD_REGISTER, PERMISSIONS.GUARD_ASSIGN_SITE,
    PERMISSIONS.GUARD_ATTENDANCE_READ, PERMISSIONS.GUARD_ATTENDANCE_MANAGE, PERMISSIONS.GUARD_ATTENDANCE_FUTURE,
    PERMISSIONS.STAFF_ATTENDANCE_MANAGE,
    PERMISSIONS.GUARD_PAYROLL_READ, PERMISSIONS.OFFICE_PAYROLL_CREATE,
    PERMISSIONS.REPORT_READ, PERMISSIONS.SETTINGS_READ,
    PERMISSIONS.ORGANIZATION_READ, PERMISSIONS.ORGANIZATION_MANAGE,
    PERMISSIONS.ROTATION_READ, PERMISSIONS.ROTATION_MANAGE, PERMISSIONS.ROTATION_GENERATE,
    PERMISSIONS.ROTATION_APPROVE, PERMISSIONS.ROTATION_PUBLISH,
    PERMISSIONS.PURCHASE_READ, PERMISSIONS.CONTACT_READ, PERMISSIONS.PRODUCT_READ,
  ],
  [UserRole.FINANCE_OFFICER]: [
    PERMISSIONS.USER_READ, PERMISSIONS.EMPLOYEE_READ, PERMISSIONS.SITE_READ,
    PERMISSIONS.COMPANY_READ, PERMISSIONS.COMPANY_UPDATE,
    PERMISSIONS.GUARD_PAYROLL_READ,
    PERMISSIONS.GUARD_PAYROLL_RATES, PERMISSIONS.GUARD_PAYROLL_CALCULATE,
    PERMISSIONS.GUARD_PAYROLL_CHECK, PERMISSIONS.GUARD_PAYROLL_PAY, PERMISSIONS.GUARD_PAYROLL_RETURN,
    PERMISSIONS.GUARD_ATTENDANCE_READ,
    PERMISSIONS.OFFICE_PAYROLL_CREATE, PERMISSIONS.OFFICE_PAYROLL_RATES, PERMISSIONS.OFFICE_PAYROLL_PAY,
    PERMISSIONS.REPORT_READ, PERMISSIONS.AUDIT_READ,
    PERMISSIONS.SETTINGS_READ, PERMISSIONS.SETTINGS_UPDATE, PERMISSIONS.PAYROLL_PERIOD_READ,
    PERMISSIONS.PURCHASE_READ, PERMISSIONS.PURCHASE_APPROVE, PERMISSIONS.CONTACT_READ, PERMISSIONS.PRODUCT_READ, PERMISSIONS.BILL_MANAGE,
  ],
  [UserRole.OPERATIONS]: [
    PERMISSIONS.EMPLOYEE_READ, PERMISSIONS.SITE_CREATE, PERMISSIONS.SITE_READ, PERMISSIONS.SITE_UPDATE,
    PERMISSIONS.COMPANY_READ,
    PERMISSIONS.GUARD_ASSIGN_SITE, PERMISSIONS.GUARD_MODIFY_HOURS,
    PERMISSIONS.GUARD_ATTENDANCE_READ, PERMISSIONS.GUARD_ATTENDANCE_MANAGE,
    PERMISSIONS.GUARD_PAYROLL_READ, PERMISSIONS.PAYROLL_PERIOD_READ, PERMISSIONS.REPORT_READ,
    PERMISSIONS.ROTATION_READ, PERMISSIONS.ROTATION_MANAGE, PERMISSIONS.ROTATION_GENERATE,
    PERMISSIONS.ROTATION_OVERRIDE,
    PERMISSIONS.PURCHASE_READ, PERMISSIONS.PURCHASE_CREATE, PERMISSIONS.PURCHASE_UPDATE, PERMISSIONS.CONTACT_READ, PERMISSIONS.PRODUCT_READ, PERMISSIONS.GRN_MANAGE,
  ],
  [UserRole.GUARD]: [
    PERMISSIONS.EMPLOYEE_READ,
    PERMISSIONS.SITE_READ, PERMISSIONS.GUARD_PAYROLL_READ,
    PERMISSIONS.GUARD_ATTENDANCE_SELF,
  ],
  [UserRole.HEAD]: [
    PERMISSIONS.USER_READ, PERMISSIONS.EMPLOYEE_READ, PERMISSIONS.SITE_READ,
    PERMISSIONS.GUARD_PAYROLL_READ,
    PERMISSIONS.GUARD_PAYROLL_APPROVE, PERMISSIONS.OFFICE_PAYROLL_APPROVE,
    PERMISSIONS.REPORT_READ, PERMISSIONS.AUDIT_READ, PERMISSIONS.SETTINGS_READ,
    PERMISSIONS.ROTATION_READ, PERMISSIONS.ROTATION_APPROVE,
    PERMISSIONS.PURCHASE_READ, PERMISSIONS.PURCHASE_APPROVE, PERMISSIONS.CONTACT_READ, PERMISSIONS.PRODUCT_READ,
  ],
  [UserRole.CEO]: [
    PERMISSIONS.USER_READ, PERMISSIONS.EMPLOYEE_READ, PERMISSIONS.SITE_READ,
    PERMISSIONS.COMPANY_READ,
    PERMISSIONS.STAFF_ATTENDANCE_MANAGE,
    PERMISSIONS.GUARD_ATTENDANCE_READ,
    PERMISSIONS.GUARD_PAYROLL_READ, PERMISSIONS.OFFICE_PAYROLL_CREATE,
    PERMISSIONS.REPORT_READ, PERMISSIONS.AUDIT_READ, PERMISSIONS.SETTINGS_READ,
    PERMISSIONS.PAYROLL_PERIOD_READ,
    PERMISSIONS.ROTATION_READ, PERMISSIONS.ROTATION_APPROVE,
    PERMISSIONS.PURCHASE_READ, PERMISSIONS.PURCHASE_CREATE, PERMISSIONS.PURCHASE_UPDATE, PERMISSIONS.PURCHASE_APPROVE, PERMISSIONS.PURCHASE_DELETE,
    PERMISSIONS.CONTACT_READ, PERMISSIONS.CONTACT_MANAGE, PERMISSIONS.PRODUCT_READ, PERMISSIONS.PRODUCT_MANAGE,
    PERMISSIONS.GRN_MANAGE, PERMISSIONS.BILL_MANAGE,
  ],
};

export interface TaxBracketEntry {
  min: number;
  max: number | null;
  rate: number;
  deduction: number;
}

export interface GuardPayrollCalculation {
  normalSalary: number;
  workedSalary: number;
  otPay: number;
  holidayPay: number;
  secondaryShiftPay: number;
  grossPay: number;
  baseComponent: number;
  employeePension: number;
  employerPension: number;
  incomeTax: number;
  totalDeductions: number;
  netPay: number;
}

export interface StaffPayrollCalculation {
  grossSalary: number;
  taxableSalary: number;
  employeePension: number;
  employerPension: number;
  incomeTax: number;
  totalDeductions: number;
  netPay: number;
}

export interface ApiResponse<T = unknown> {
  success: boolean;
  message: string;
  data?: T;
  error?: string;
}

export interface PaginatedResponse<T> {
  success: boolean;
  data: T[];
  pagination: {
    page: number;
    limit: number;
    total: number;
    totalPages: number;
  };
}
