import {
  OrganizationIcon,
  RecruitmentIcon,
  EmployeeIcon,
  CompanyIcon,
  OperationsIcon,
  SitesIcon,
  AttendanceIcon,
  SalaryStructureIcon,
  PayrollIcon,
  StaffPayrollIcon,
  ProjectIcon,
  FleetIcon,
  CRMIcon,
  ReportsIcon,
  ControlTowerIcon,
  GuardFilingIcon,
  SettingsIcon,
  PayrollConfigIcon,
} from '../components/ModuleIcons';
import { UserRole } from '../types';
import type React from 'react';

export interface SubFeature {
  label: string;
  route: string;
  icon?: React.FC<{ size?: number; className?: string }>;
}

export interface ModuleDef {
  id: string;
  label: string;
  subtitle: string;
  route: string | null;
  icon: React.FC<{ size?: number; className?: string }>;
  color: string;
  bg: string;
  text: string;
  border: string;
  hoverBorder: string;
  arrowBg: string;
  arrowText: string;
  roles: UserRole[];
  active: boolean;
  groupId?: string;
}

export interface ModuleGroup {
  id: string;
  label: string;
  color: string;
  bg: string;
  text: string;
  borderColor: string;
  navBg: string;
  subFeatures: SubFeature[];
  roles: UserRole[];
}

export const MODULE_GROUPS: ModuleGroup[] = [
  {
    id: 'hr',
    label: 'HR & People',
    color: '#7C3AED',
    bg: 'bg-violet-50',
    text: 'text-violet-600',
    borderColor: 'border-violet-200',
    navBg: 'bg-white border-b border-gray-100',
    subFeatures: [
      { label: 'Employees', route: '/employees', icon: EmployeeIcon },
      { label: 'Staff Attendance', route: '/staff-attendance', icon: AttendanceIcon },
    ],
    roles: [UserRole.SUPER_ADMIN, UserRole.SYSTEM_ADMIN, UserRole.HR_ADMIN, UserRole.CEO],
  },
  {
    id: 'ops',
    label: 'Operations',
    color: '#2563EB',
    bg: 'bg-blue-50',
    text: 'text-blue-600',
    borderColor: 'border-blue-200',
    navBg: 'bg-white border-b border-gray-100',
    subFeatures: [
      { label: 'Guard Attendance', route: '/attendance', icon: GuardFilingIcon },
      { label: 'Sites', route: '/sites', icon: SitesIcon },
      { label: 'Guards', route: '/guards', icon: OperationsIcon },
      { label: 'Rotations', route: '/rotations', icon: OperationsIcon },
    ],
    roles: [UserRole.SUPER_ADMIN, UserRole.SYSTEM_ADMIN, UserRole.OPERATIONS, UserRole.CEO],
  },
  {
    id: 'payroll',
    label: 'Payroll',
    color: '#D97706',
    bg: 'bg-amber-50',
    text: 'text-amber-600',
    borderColor: 'border-amber-200',
    navBg: 'bg-white border-b border-gray-100',
    subFeatures: [
      { label: 'Guard Payroll', route: '/guard-payroll', icon: PayrollIcon },
      { label: 'Staff Payroll', route: '/staff-payroll', icon: StaffPayrollIcon },
    ],
    roles: [UserRole.SUPER_ADMIN, UserRole.SYSTEM_ADMIN, UserRole.HR_ADMIN, UserRole.FINANCE_OFFICER, UserRole.HEAD, UserRole.CEO],
  },
  {
    id: 'finance',
    label: 'Finance',
    color: '#0D9488',
    bg: 'bg-teal-50',
    text: 'text-teal-600',
    borderColor: 'border-teal-200',
    navBg: 'bg-white border-b border-gray-100',
    subFeatures: [
      { label: 'Control Tower', route: '/finance', icon: ControlTowerIcon },
      { label: 'Finance Review', route: '/guard-payroll/review' },
    ],
    roles: [UserRole.SUPER_ADMIN, UserRole.SYSTEM_ADMIN, UserRole.FINANCE_OFFICER, UserRole.CEO],
  },
  {
    id: 'reports',
    label: 'Reports',
    color: '#4F46E5',
    bg: 'bg-indigo-50',
    text: 'text-indigo-600',
    borderColor: 'border-indigo-200',
    navBg: 'bg-white border-b border-gray-100',
    subFeatures: [
      { label: 'Reports', route: '/reports', icon: ReportsIcon },
    ],
    roles: [UserRole.SUPER_ADMIN, UserRole.SYSTEM_ADMIN, UserRole.HR_ADMIN, UserRole.FINANCE_OFFICER, UserRole.OPERATIONS, UserRole.HEAD, UserRole.CEO],
  },
  {
    id: 'admin',
    label: 'Administration',
    color: '#475569',
    bg: 'bg-slate-50',
    text: 'text-slate-600',
    borderColor: 'border-slate-200',
    navBg: 'bg-white border-b border-gray-100',
    subFeatures: [
      { label: 'Settings', route: '/settings', icon: SettingsIcon },
      { label: 'Salary Structures', route: '/admin/salary-structures', icon: SalaryStructureIcon },
      { label: 'Payroll Config', route: '/admin/payroll-config', icon: PayrollConfigIcon },
    ],
    roles: [UserRole.SUPER_ADMIN, UserRole.SYSTEM_ADMIN, UserRole.FINANCE_OFFICER, UserRole.CEO],
  },
];

const ALL_ROLES: UserRole[] = [
  UserRole.SUPER_ADMIN, UserRole.SYSTEM_ADMIN, UserRole.HR_ADMIN,
  UserRole.FINANCE_OFFICER, UserRole.OPERATIONS, UserRole.HEAD, UserRole.GUARD, UserRole.CEO,
];

export const MODULES: ModuleDef[] = [
  {
    id: 'organization',
    label: 'Organization',
    subtitle: 'Manage your company structure and settings.',
    route: '/settings',
    icon: OrganizationIcon,
    color: '#6366F1',
    bg: 'bg-indigo-50',
    text: 'text-indigo-600',
    border: 'border-indigo-100',
    hoverBorder: 'hover:border-indigo-300',
    arrowBg: 'bg-indigo-100',
    arrowText: 'text-indigo-600',
    roles: [UserRole.SUPER_ADMIN, UserRole.SYSTEM_ADMIN, UserRole.CEO],
    active: true,
    groupId: 'admin',
  },
  {
    id: 'recruitment',
    label: 'Recruitment',
    subtitle: 'Handle job postings, applications and hiring.',
    route: null,
    icon: RecruitmentIcon,
    color: '#14B8A6',
    bg: 'bg-teal-50',
    text: 'text-teal-600',
    border: 'border-teal-100',
    hoverBorder: 'hover:border-teal-300',
    arrowBg: 'bg-teal-100',
    arrowText: 'text-teal-600',
    roles: ALL_ROLES,
    active: false,
  },
  {
    id: 'employee',
    label: 'Employee',
    subtitle: 'Manage employee records and information.',
    route: '/employees',
    icon: EmployeeIcon,
    color: '#7C3AED',
    bg: 'bg-violet-50',
    text: 'text-violet-600',
    border: 'border-violet-100',
    hoverBorder: 'hover:border-violet-300',
    arrowBg: 'bg-violet-100',
    arrowText: 'text-violet-600',
    roles: [UserRole.SUPER_ADMIN, UserRole.SYSTEM_ADMIN, UserRole.HR_ADMIN, UserRole.CEO],
    active: true,
    groupId: 'hr',
  },
  {
    id: 'company',
    label: 'Company',
    subtitle: 'Company details and basic settings.',
    route: null,
    icon: CompanyIcon,
    color: '#0D9488',
    bg: 'bg-teal-50',
    text: 'text-teal-600',
    border: 'border-teal-100',
    hoverBorder: 'hover:border-teal-300',
    arrowBg: 'bg-teal-100',
    arrowText: 'text-teal-600',
    roles: ALL_ROLES,
    active: false,
  },
  {
    id: 'ops',
    label: 'Operations',
    subtitle: 'Manage daily operations and workflows.',
    route: '/sites',
    icon: OperationsIcon,
    color: '#2563EB',
    bg: 'bg-blue-50',
    text: 'text-blue-600',
    border: 'border-blue-100',
    hoverBorder: 'hover:border-blue-300',
    arrowBg: 'bg-blue-100',
    arrowText: 'text-blue-600',
    roles: [UserRole.SUPER_ADMIN, UserRole.SYSTEM_ADMIN, UserRole.OPERATIONS, UserRole.CEO],
    active: true,
    groupId: 'ops',
  },
  {
    id: 'attendance',
    label: 'Attendance',
    subtitle: 'Track attendance for staff and guards.',
    route: '/staff-attendance',
    icon: AttendanceIcon,
    color: '#F59E0B',
    bg: 'bg-amber-50',
    text: 'text-amber-600',
    border: 'border-amber-100',
    hoverBorder: 'hover:border-amber-300',
    arrowBg: 'bg-amber-100',
    arrowText: 'text-amber-600',
    roles: [UserRole.SUPER_ADMIN, UserRole.SYSTEM_ADMIN, UserRole.HR_ADMIN, UserRole.CEO],
    active: true,
    groupId: 'hr',
  },
  {
    id: 'salary',
    label: 'Salary Structure',
    subtitle: 'Define salaries and allowances.',
    route: '/admin/salary-structures',
    icon: SalaryStructureIcon,
    color: '#F59E0B',
    bg: 'bg-amber-50',
    text: 'text-amber-600',
    border: 'border-amber-100',
    hoverBorder: 'hover:border-amber-300',
    arrowBg: 'bg-amber-100',
    arrowText: 'text-amber-600',
    roles: [UserRole.SUPER_ADMIN, UserRole.SYSTEM_ADMIN, UserRole.CEO],
    active: true,
    groupId: 'admin',
  },
  
  {
    id: 'payroll',
    label: 'Payroll',
    subtitle: 'Process and manage guard payroll.',
    route: '/guard-payroll',
    icon: PayrollIcon,
    color: '#D97706',
    bg: 'bg-amber-50',
    text: 'text-amber-600',
    border: 'border-amber-100',
    hoverBorder: 'hover:border-amber-300',
    arrowBg: 'bg-amber-100',
    arrowText: 'text-amber-600',
    roles: [UserRole.SUPER_ADMIN, UserRole.SYSTEM_ADMIN, UserRole.HR_ADMIN, UserRole.FINANCE_OFFICER, UserRole.HEAD, UserRole.CEO],
    active: true,
    groupId: 'payroll',
  },
  {
    id: 'staff-payroll',
    label: 'Staff Payroll',
    subtitle: 'Process and manage office staff payroll.',
    route: '/staff-payroll',
    icon: StaffPayrollIcon,
    color: '#D97706',
    bg: 'bg-amber-50',
    text: 'text-amber-600',
    border: 'border-amber-100',
    hoverBorder: 'hover:border-amber-300',
    arrowBg: 'bg-amber-100',
    arrowText: 'text-amber-600',
    roles: [UserRole.SUPER_ADMIN, UserRole.SYSTEM_ADMIN, UserRole.HR_ADMIN, UserRole.FINANCE_OFFICER, UserRole.HEAD, UserRole.CEO],
    active: true,
    groupId: 'payroll',
  },
  
  {
    id: 'project',
    label: 'Project Management',
    subtitle: 'Tasks, milestones, time tracking, resource allocation.',
    route: null,
    icon: ProjectIcon,
    color: '#6366F1',
    bg: 'bg-indigo-50',
    text: 'text-indigo-600',
    border: 'border-indigo-100',
    hoverBorder: 'hover:border-indigo-300',
    arrowBg: 'bg-indigo-100',
    arrowText: 'text-indigo-600',
    roles: ALL_ROLES,
    active: false,
  },
  {
    id: 'fleet',
    label: 'Fleet Management',
    subtitle: 'Vehicles, maintenance, fuel tracking, assignments.',
    route: null,
    icon: FleetIcon,
    color: '#7C3AED',
    bg: 'bg-purple-50',
    text: 'text-purple-600',
    border: 'border-purple-100',
    hoverBorder: 'hover:border-purple-300',
    arrowBg: 'bg-purple-100',
    arrowText: 'text-purple-600',
    roles: ALL_ROLES,
    active: false,
  },
 
  {
    id: 'crm',
    label: 'Sales & CRM',
    subtitle: 'Leads, opportunities, customer relationships.',
    route: null,
    icon: CRMIcon,
    color: '#14B8A6',
    bg: 'bg-teal-50',
    text: 'text-teal-600',
    border: 'border-teal-100',
    hoverBorder: 'hover:border-teal-300',
    arrowBg: 'bg-teal-100',
    arrowText: 'text-teal-600',
    roles: ALL_ROLES,
    active: false,
  },
  {
    id: 'reports',
    label: 'Reports',
    subtitle: 'Analytics & insights.',
    route: '/reports',
    icon: ReportsIcon,
    color: '#4F46E5',
    bg: 'bg-indigo-50',
    text: 'text-indigo-600',
    border: 'border-indigo-100',
    hoverBorder: 'hover:border-indigo-300',
    arrowBg: 'bg-indigo-100',
    arrowText: 'text-indigo-600',
    roles: [UserRole.SUPER_ADMIN, UserRole.SYSTEM_ADMIN, UserRole.HR_ADMIN, UserRole.FINANCE_OFFICER, UserRole.OPERATIONS, UserRole.HEAD, UserRole.CEO],
    active: true,
    groupId: 'reports',
  },
  {
    id: 'control',
    label: 'Control Tower',
    subtitle: 'Real-time monitoring and oversight.',
    route: '/finance',
    icon: ControlTowerIcon,
    color: '#0D9488',
    bg: 'bg-teal-50',
    text: 'text-teal-600',
    border: 'border-teal-100',
    hoverBorder: 'hover:border-teal-300',
    arrowBg: 'bg-teal-100',
    arrowText: 'text-teal-600',
    roles: [UserRole.SUPER_ADMIN, UserRole.SYSTEM_ADMIN, UserRole.FINANCE_OFFICER, UserRole.CEO],
    active: true,
    groupId: 'finance',
  },
  {
    id: 'guard-filing',
    label: 'Guard Filing',
    subtitle: 'File and manage guard attendance records.',
    route: '/attendance',
    icon: GuardFilingIcon,
    color: '#2563EB',
    bg: 'bg-blue-50',
    text: 'text-blue-600',
    border: 'border-blue-100',
    hoverBorder: 'hover:border-blue-300',
    arrowBg: 'bg-blue-100',
    arrowText: 'text-blue-600',
    roles: [UserRole.SUPER_ADMIN, UserRole.SYSTEM_ADMIN, UserRole.OPERATIONS, UserRole.CEO],
    active: true,
    groupId: 'ops',
  },/*
{
    id: 'leave',
    label: 'Leave Settings',
    subtitle: 'Manage leave types and policies.',
    route: null,
    icon: LeaveIcon,
    color: '#EC4899',
    bg: 'bg-pink-50',
    text: 'text-pink-600',
    border: 'border-pink-100',
    hoverBorder: 'hover:border-pink-300',
    arrowBg: 'bg-pink-100',
    arrowText: 'text-pink-600',
    roles: ALL_ROLES,
    active: false,
  },
{
    id: 'adjustment',
    label: 'Salary Adjustment',
    subtitle: 'Adjust and update salaries.',
    route: null,
    icon: SalaryAdjustmentIcon,
    color: '#10B981',
    bg: 'bg-emerald-50',
    text: 'text-emerald-600',
    border: 'border-emerald-100',
    hoverBorder: 'hover:border-emerald-300',
    arrowBg: 'bg-emerald-100',
    arrowText: 'text-emerald-600',
    roles: ALL_ROLES,
    active: false,
  },
   {
    id: 'procurement',
    label: 'Procurement',
    subtitle: 'Purchase requests, vendor management, approvals.',
    route: null,
    icon: ProcurementIcon,
    color: '#10B981',
    bg: 'bg-emerald-50',
    text: 'text-emerald-600',
    border: 'border-emerald-100',
    hoverBorder: 'hover:border-emerald-300',
    arrowBg: 'bg-emerald-100',
    arrowText: 'text-emerald-600',
    roles: ALL_ROLES,
    active: false,
  },
  {
    id: 'manufacturing',
    label: 'Manufacturing',
    subtitle: 'Production orders, BOM, work centers.',
    route: null,
    icon: ManufacturingIcon,
    color: '#6366F1',
    bg: 'bg-indigo-50',
    text: 'text-indigo-600',
    border: 'border-indigo-100',
    hoverBorder: 'hover:border-indigo-300',
    arrowBg: 'bg-indigo-100',
    arrowText: 'text-indigo-600',
    roles: ALL_ROLES,
    active: false,
  },
  {
  {
    id: 'sites',
    label: 'Sites',
    subtitle: 'Manage and monitor client site locations.',
    route: '/sites',
    icon: SitesIcon,
    color: '#2563EB',
    bg: 'bg-blue-50',
    text: 'text-blue-600',
    border: 'border-blue-100',
    hoverBorder: 'hover:border-blue-300',
    arrowBg: 'bg-blue-100',
    arrowText: 'text-blue-600',
    roles: [UserRole.SUPER_ADMIN, UserRole.SYSTEM_ADMIN, UserRole.HR_ADMIN, UserRole.FINANCE_OFFICER, UserRole.OPERATIONS, UserRole.CEO],
    active: true,
    groupId: 'ops',
  },
  {
    id: 'sign',
    label: 'Sign Note',
    subtitle: 'Digital notes and official sign-offs.',
    route: null,
    icon: SignNoteIcon,
    color: '#F59E0B',
    bg: 'bg-amber-50',
    text: 'text-amber-600',
    border: 'border-amber-100',
    hoverBorder: 'hover:border-amber-300',
    arrowBg: 'bg-amber-100',
    arrowText: 'text-amber-600',
    roles: ALL_ROLES,
    active: false,
  },
 
    id: 'admin',
    label: 'Administration',
    subtitle: 'System settings and configuration.',
    route: '/settings',
    icon: SettingsIcon,
    color: '#475569',
    bg: 'bg-slate-50',
    text: 'text-slate-600',
    border: 'border-slate-100',
    hoverBorder: 'hover:border-slate-300',
    arrowBg: 'bg-slate-100',
    arrowText: 'text-slate-600',
    roles: [UserRole.SUPER_ADMIN, UserRole.SYSTEM_ADMIN, UserRole.FINANCE_OFFICER, UserRole.CEO],
    active: true,
    groupId: 'admin',
  },
  {
    id: 'payroll-config',
    label: 'Payroll Config',
    subtitle: 'Configure payroll formula engine and rules.',
    route: '/admin/payroll-config',
    icon: PayrollConfigIcon,
    color: '#7C3AED',
    bg: 'bg-purple-50',
    text: 'text-purple-600',
    border: 'border-purple-100',
    hoverBorder: 'hover:border-purple-300',
    arrowBg: 'bg-purple-100',
    arrowText: 'text-purple-600',
    roles: [UserRole.SUPER_ADMIN, UserRole.CEO],
    active: true,
    groupId: 'admin',
  },*/
];

const ROUTE_OVERRIDES: { pattern: RegExp; groupId: string }[] = [
  { pattern: /^\/employees(\/.*)?$/, groupId: 'hr' },
  { pattern: /^\/staff-attendance\/summary$/, groupId: 'finance' },
  { pattern: /^\/staff-attendance(\/.*)?$/, groupId: 'hr' },
  { pattern: /^\/sites(\/.*)?$/, groupId: 'ops' },
  { pattern: /^\/guards(\/.*)?$/, groupId: 'ops' },
  { pattern: /^\/attendance(\/.*)?$/, groupId: 'ops' },
  { pattern: /^\/rotations(\/.*)?$/, groupId: 'ops' },
  { pattern: /^\/guard-payroll\/review$/, groupId: 'finance' },
  { pattern: /^\/guard-payroll(\/.*)?$/, groupId: 'payroll' },
  { pattern: /^\/staff-payroll(\/.*)?$/, groupId: 'payroll' },
  { pattern: /^\/finance(\/.*)?$/, groupId: 'finance' },
  { pattern: /^\/reports(\/.*)?$/, groupId: 'reports' },
  { pattern: /^\/settings(\/.*)?$/, groupId: 'admin' },
  { pattern: /^\/contracts(\/.*)?$/, groupId: 'hr' },
  { pattern: /^\/admin\/salary-structures$/, groupId: 'admin' },
  { pattern: /^\/admin\/payroll-config$/, groupId: 'admin' },
];

export function getModuleGroupForRoute(pathname: string): ModuleGroup | null {
  for (const override of ROUTE_OVERRIDES) {
    if (override.pattern.test(pathname)) {
      return MODULE_GROUPS.find((g) => g.id === override.groupId) || null;
    }
  }
  for (const group of MODULE_GROUPS) {
    for (const sf of group.subFeatures) {
      const sfPath = sf.route.split('?')[0];
      if (pathname === sfPath) {
        return group;
      }
    }
  }
  return null;
}

export function getModuleGroupById(groupId: string): ModuleGroup | undefined {
  return MODULE_GROUPS.find((g) => g.id === groupId);
}
