/** Report-page labels (en + am). Kept local to the reports feature so the
 *  shared DictKey dictionaries stay untouched. */
const en = {
  repTitle: 'Reports',
  repSubtitle: 'Filterable report for every module — filter, export to CSV, or print.',
  repNoAccess: 'You do not have access to reports.',
  repTabHr: 'HR',
  repTabSites: 'Sites',
  repTabGuards: 'Guards',
  repTabGuardAtt: 'Guard Attendance',
  repTabStaffAtt: 'Staff Attendance',
  repTabPayroll: 'Payroll',
  repTabAudit: 'Audit Trail',
  repTabUsers: 'Users',
  repApply: 'Apply',
  repJoinedFrom: 'Joined from',
  repJoinedTo: 'Joined to',
  repSiteType: 'Site type',
  repSiteId: 'Site ID',
  repMonth: 'Month',
  repModule: 'Payroll module',
  repAction: 'Action',
  repEntity: 'Entity',
  repEntityId: 'Entity ID',
  repFrom: 'From',
  repTo: 'To',
  repDate: 'Date',
  repUser: 'User',
  repReason: 'Reason',
  repIp: 'IP',
  repEmail: 'Email',
  repLastLogin: 'Last login',
  repHours: 'Hours',
  repHoliday: 'Holiday',
  repSource: 'Source',
  repLeave: 'Leave type',
  repNotes: 'Notes',
  repGross: 'Gross',
  repTaxable: 'Taxable',
  repEmpPension: 'Employee pension',
  repTax: 'Income tax',
  repDeductions: 'Deductions',
  repNet: 'Net pay',
  repBasic: 'Basic salary',
  repBank: 'Bank',
  repAccount: 'Account',
  repSiteName: 'Site',
  repClient: 'Client',
  repLocation: 'Location',
  repAgreed: 'Agreed manpower',
  repActual: 'Actual manpower',
  repComp: 'Compensation',
  repAgreeFrom: 'Agreement start',
  repAgreeTo: 'Agreement end',
  repPrimarySite: 'Primary site',
  repNormalH: 'Normal h',
  repHolidayH: 'Holiday h',
  repSundayH: 'Sunday h',
  repInactive: 'Inactive',
  repYes: 'Yes',

  // Shared labels reused by report columns/buttons
  search: 'Search',
  month: 'Month',
  period: 'Period',
  status: 'Status',
  active: 'Active',
  department: 'Department',
  category: 'Category',
  role: 'Role',
  fullName: 'Full Name',
  employeeId: 'Employee ID',
  joinDate: 'Join Date',
  phone: 'Phone',
  email: 'Email',
  print: 'Print',
  exportCsv: 'Export CSV',
  noData: 'No data',
};

const am: typeof en = {
  repTitle: 'ሪፖርቶች',
  repSubtitle: 'ለሁሉም ሞዱል በማጣሪያ የሚታይ ሪፖርት — ያጣራ፣ CSV አውጣ ወይም አትም።',
  repNoAccess: 'ሪፖርቶችን ለማየት ፈቃድ የለዎትም።',
  repTabHr: 'ሰው ኃይል',
  repTabSites: 'ጣቢያዎች',
  repTabGuards: 'ጠባቂዎች',
  repTabGuardAtt: 'የጠባቂዎች አጀንዳ',
  repTabStaffAtt: 'የሠራተኛ አጀንዳ',
  repTabPayroll: 'ደመወዝ',
  repTabAudit: 'የስራ መዝገብ',
  repTabUsers: 'ተጠቃሚዎች',
  repApply: 'ተግብር',
  repJoinedFrom: 'ከቀን',
  repJoinedTo: 'እስከ ቀን',
  repSiteType: 'የጣቢያ አይነት',
  repSiteId: 'የጣቢያ መለያ',
  repMonth: 'ወር',
  repModule: 'የደመወዝ ሞዱል',
  repAction: 'እርምጃ',
  repEntity: 'አካል',
  repEntityId: 'መለያ',
  repFrom: 'ከ',
  repTo: 'እስከ',
  repDate: 'ቀን',
  repUser: 'ተጠቃሚ',
  repReason: 'ምክንያት',
  repIp: 'IP',
  repEmail: 'ኢሜይል',
  repLastLogin: 'መጨረሻ ግቢያ',
  repHours: 'ሰዓት',
  repHoliday: 'በዓል',
  repSource: 'ምንጭ',
  repLeave: 'የፍቃድ አይነት',
  repNotes: 'ማስታወሻ',
  repGross: 'አጠቃላይ',
  repTaxable: 'ተገቢ የሆነ',
  repEmpPension: 'የሠራተኛ ጡረታ',
  repTax: 'ተገቢ ግብር',
  repDeductions: 'ተቀናሾች',
  repNet: 'የሚከፈል',
  repBasic: 'የመሰረት ደመወዝ',
  repBank: 'ባንክ',
  repAccount: 'ሒሳብ ቁጥር',
  repSiteName: 'ጣቢያ',
  repClient: 'ደንበኛ',
  repLocation: 'አድራሻ',
  repAgreed: 'የተስማማ ሰው ብዛት',
  repActual: 'ካለ ሰው ብዛት',
  repComp: 'ካሳ',
  repAgreeFrom: 'ውል ጀምሮ',
  repAgreeTo: 'ውል እስከ',
  repPrimarySite: 'ዋና ጣቢያ',
  repNormalH: 'መደበኛ ሰዓት',
  repHolidayH: 'የበዓል ሰዓት',
  repSundayH: 'የእሁድ ሰዓት',
  repInactive: 'ንቁ ያልሆነ',
  repYes: 'አዎ',

  // Shared labels reused by report columns/buttons
  search: 'ፈልግ',
  month: 'ወር',
  period: 'ወቅት',
  status: 'ሁኔታ',
  active: 'ንቁ',
  department: 'ክፍል',
  category: 'ምድብ',
  role: 'ሚና',
  fullName: 'ሙሉ ስም',
  employeeId: 'የሠራተኛ መለያ',
  joinDate: 'የተቀላቀሉበት ቀን',
  phone: 'ስልክ',
  email: 'ኢሜይል',
  print: 'አትም',
  exportCsv: 'CSV አውጣ',
  noData: 'መረጃ የለም',
};

export type ReportLang = 'en' | 'am';

const dicts: Record<ReportLang, typeof en> = { en, am };

export function useRepT(lang: ReportLang) {
  return (key: string) => (dicts[lang] as Record<string, string>)?.[key] ?? (dicts.en as Record<string, string>)[key] ?? key;
}
